project_name: speedtest-exporter

before:
  hooks:
    - go mod tidy

builds:
  - env:
      - CGO_ENABLED=0
    goos:
      - linux
      - windows
      - darwin
    goarch:
      - amd64
      - arm64
    ldflags:
      - -s -w -X main.version={{.Version}}

archives:
  - format: tar.gz
    name_template: >-
      {{ .ProjectName }}_
      {{- title .Os }}_
      {{- if eq .Arch "amd64" }}x86_64
      {{- else if eq .Arch "386" }}i386
      {{- else }}{{ .Arch }}{{ end }}
      {{- if .Arm }}v{{ .Arm }}{{ end }}
    format_overrides:
      - goos: windows
        format: zip

checksum:
  name_template: 'checksums.txt'

snapshot:
  name_template: "{{ incpatch .Version }}-next"

changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'

dockers:
  - image_templates:
      - "ghcr.io/dkarter/speedtest-exporter:{{ .Tag }}-amd64"
      - "ghcr.io/dkarter/speedtest-exporter:latest-amd64"
    dockerfile: Dockerfile
    use: buildx
    goos: linux
    goarch: amd64
    build_flag_templates:
      - "--pull"
      - "--platform=linux/amd64"
      - "--label=org.opencontainers.image.created={{.Date}}"
      - "--label=org.opencontainers.image.title={{.ProjectName}}"
      - "--label=org.opencontainers.image.revision={{.FullCommit}}"
      - "--label=org.opencontainers.image.version={{.Version}}"
      - "--label=org.opencontainers.image.source=https://github.com/dkarter/speedtest-exporter"
  - image_templates:
      - "ghcr.io/dkarter/speedtest-exporter:{{ .Tag }}-arm64"
      - "ghcr.io/dkarter/speedtest-exporter:latest-arm64"
    dockerfile: Dockerfile
    use: buildx
    goos: linux
    goarch: arm64
    build_flag_templates:
      - "--pull"
      - "--platform=linux/arm64"
      - "--label=org.opencontainers.image.created={{.Date}}"
      - "--label=org.opencontainers.image.title={{.ProjectName}}"
      - "--label=org.opencontainers.image.revision={{.FullCommit}}"
      - "--label=org.opencontainers.image.version={{.Version}}"
      - "--label=org.opencontainers.image.source=https://github.com/dkarter/speedtest-exporter"

docker_manifests:
  - name_template: "ghcr.io/dkarter/speedtest-exporter:{{ .Tag }}"
    image_templates:
      - "ghcr.io/dkarter/speedtest-exporter:{{ .Tag }}-amd64"
      - "ghcr.io/dkarter/speedtest-exporter:{{ .Tag }}-arm64"
  - name_template: "ghcr.io/dkarter/speedtest-exporter:latest"
    image_templates:
      - "ghcr.io/dkarter/speedtest-exporter:latest-amd64"
      - "ghcr.io/dkarter/speedtest-exporter:latest-arm64"
